### ISSUE TITLE
meet TypeError while using cmd '/wns'

### ISSUE THREAD

**Issue by dadwadw233** [daxcay/ComfyUI-TG#2]
full error:
```sh
TypeError: Cannot read properties of undefined (reading 'title')
    at extractTitleFromModel (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:176:35)
    at setCommand (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:387:7)
    at TelegramBot.<anonymous> (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:553:4)
    at TelegramBot.emit (/home/ssd/yyh/code/playground/ComfyUI/node_modules/eventemitter3/index.js:182:35)
    at TelegramBot.processUpdate (/home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegram.js:709:14)
    at /home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at /home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegramPolling.js:106:17
    at tryCatcher (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)
From: Y Command: /wns 0 Type: text
TypeError: Cannot read properties of undefined (reading 'title')
    at extractTitleFromModel (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:176:35)
    at setCommand (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:387:7)
    at TelegramBot.<anonymous> (/home/ssd/yyh/code/playground/ComfyUI/custom_nodes/ComfyUI-TG/nodejs/project/app.js:553:4)
    at TelegramBot.emit (/home/ssd/yyh/code/playground/ComfyUI/node_modules/eventemitter3/index.js:182:35)
    at TelegramBot.processUpdate (/home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegram.js:709:14)
    at /home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegramPolling.js:110:22
    at Array.forEach (<anonymous>)
    at /home/ssd/yyh/code/playground/ComfyUI/node_modules/node-telegram-bot-api/src/telegramPolling.js:106:17
    at tryCatcher (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/ssd/yyh/code/playground/ComfyUI/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)

**Comment by dadwadw233** [comment]
i think the error maybe come from wrong version of comfyui? @daxcay what version is used while dev this extension?

**Comment by daxcay** [comment]
One possible reason for this is you are not saving the workflow in api version.

**Comment by dadwadw233** [comment]
> One possible reason for this is you are not saving the workflow in api version.

! you re right :smiley: , thanks for the great job :+1:
